### ISSUE TITLE
Tone Color Converter and Base Speaker

### ISSUE THREAD

**Issue by HanzVivatma** [myshell-ai/OpenVoice#12]
Hello,

Your model and paper look great.
I am deeply impressed for the ability to mimic the tone voice of your model. I tested on English and the results were so good. 
However, when I tested ToneColorConverter on Vietnamese, the results were not as good as that of English. It even mistakes femle's tone voice for male's tone voice. An explaination for this result could be that ToneColorConverter was not trained on Vietnamese datasets so it may not capture special features on Vietnamese.

Could you please suggest some measures to solve this problem?

And I also look forward to your new plan for training the base speaker model and tone color converter model on the custom datasets.

Thank you.

**Comment by HanzVivatma** [comment]
one more question,
tone_color_converter.convert(
        audio_src_path=src_path, 
        src_se=source_se, 
        tgt_se=target_se, 
        output_path=save_path,
        message=encode_message)

Is there any difference between the voice of src_se and the voice of audio_src_path? Could I set that the value of src_se is generated from the voice of audio_src_path?

**Comment by Zengyi-Qin** [comment]
There might be some issues with how you extract the se. src_se should be extracted from a relatively long+clean audio (30s) if you wanted to obtain a high-quality se. audio_src_path could be as short as one sentence.

**Comment by HanzVivatma** [comment]
I try to follow your suggestions but the voice results still seem to be dissimilar with the reference voices

**Comment by Zengyi-Qin** [comment]
You can try inputing Vietnamese to demo_part2.ipynb and see if it works. 
![image](https://github.com/myshell-ai/OpenVoice/assets/40556743/0c61e00b-1ad8-4409-b112-e64482bdeec2)
