### ISSUE TITLE
[Question] Can I fintune speaker embbeding feature?

### ISSUE THREAD

**Issue by phamkhactu** [myshell-ai/OpenVoice#127]
Thanks for excellent work.

I see that when cloning voice, I must extract speaker emb. However, pre-trained model is only good for E, another language isn't
How can I fintune it? if not, how can I get it? How about pretrained base TTS such as coqui-ai,..?

Thanks very much!

**Comment by Zengyi-Qin** [comment]
Finetuning the embedding is not supported. If you tried a base speaker and it doesn't work well, simply try another speaker. In our observations, some base speakers does work not as good as others.
