### ISSUE TITLE
please support mac m1/m2/m3 mps metal

### ISSUE THREAD

**Issue by ehartford** [myshell-ai/OpenVoice#133]
seriously.

**Comment by Zengyi-Qin** [comment]
This is not a single-point problem. The repo has many dependencies that hasn't been adapted for apple chips

**Comment by ehartford** [comment]
Actually, I dug into this and it works pretty much out of the box.
Just need to install pytorch for mps and need to `pip install torch` `brew install ffmpeg` and `pip install chardet` other than that follow the readme and the demo ipynb

**Comment by hk6an6** [comment]
I'm confused. The demo ipynb sets the device to "cuda:0" and when I change that to "mps"  it breaks.

It seems openvoice/attentions.py finds that there's a dimension missing in a tensor and it errors with:

```
File "/Users/nico/openvoice/OpenVoice/openvoice/attentions.py", line 350, in _get_relative_embeddings
    padded_relative_embeddings = F.pad(
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
```

**Comment by AI-Guru** [comment]
I followed @ehartford's instructions and got OpenVoice on MPS up and running in no time. The only thing that I had to do was setting PYTORCH_ENABLE_MPS_FALLBACK to 1. Should this trouble me?

**Comment by hk6an6** [comment]
No worries. You are good.

Apple’s Metal does not yet have support for every operation in PyTorch. You
are supplementing the gaps with your CPU.

**Comment by smartexpert** [comment]
> Actually, I dug into this and it works pretty much out of the box. Just need to install pytorch for mps and need to `pip install torch` `brew install ffmpeg` and `pip install chardet` other than that follow the readme and the demo ipynb

Can confirm I was able to run it successfully on M3 using these instructions.

**Comment by hk6an6** [comment]
Yes it works following the instructions.

Do you know of your M3 is using its GPU cores or the neural engine instead
of the CPU cores?
