### ISSUE TITLE
ZH_style_base_model

### ISSUE THREAD

**Issue by WinterStraw** [myshell-ai/OpenVoice#15]
Thank you very much for your contributions. This is a very useful and clear open-source project.

I noticed that it performed surprisingly well on English tasks. However, there seem to be some potential areas for improvement in the Chinese task, such as the lack of a style model that can adjust emotions.

Do you plan to release the relevant training process in the future, such as data and code?  I want to try to fine-tune the Chinese base model and train the style-model. Thanks a lot.

**Comment by Zengyi-Qin** [comment]
We are indeed workinig on a new project that will opensource the data, with diverse emotion/styles, for both Chinese and English. Stay tuned!

**Comment by minguilong** [comment]
how to use?
