### ISSUE TITLE
V2 bucket link is broken, please fix

### ISSUE THREAD

**Issue by ajram23** [myshell-ai/OpenVoice#173]
https://myshell-public-repo-hosting.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip

**Comment by Zengyi-Qin** [comment]
It works on my side.

**Comment by ajram23** [comment]
Finally works for me. Closing ticket.

**Comment by elvissantos1979** [comment]
cara não consigo baixar esses checkpoints
