### ISSUE TITLE
Question about training details

### ISSUE THREAD

**Issue by ethanyhzhang** [myshell-ai/OpenVoice#19]
Hi, 
    Thanks again for your nice work. Here is another questions:
     (1) There are two stages for training convertor, how long should each stage train?
     (2) How long (or iterations) could we get a model which performs like the one you provided?

> I haved trained for nearly 30w iters, but the result is too bad.

thx again and looking forward to your reply ^_^

**Comment by Zengyi-Qin** [comment]
The converter only needs a single-stage training. Typically 100 epochs should be sufficient

**Comment by ethanyhzhang** [comment]
thx, I'll try to train for more time.

**Comment by lsrami** [comment]
> Hi, Thanks again for your nice work. Here is another questions: (1) There are two stages for training convertor, how long should each stage train? (2) How long (or iterations) could we get a model which performs like the one you provided?
> 
> > I haved trained for nearly 30w iters, but the result is too bad.
> 
> thx again and looking forward to your reply ^_^

我看到代码只有推理部分，没有训练部分，您有关于训练的相关细节可以分享吗，比如forward函数
