### ISSUE TITLE
Notebook? Files?

### ISSUE THREAD

**Issue by cchance27** [myshell-ai/OpenVoice#2]
Really awesome looking paper and samples was anxious to try but seems the repo's empty or is there a different repo we should be tracking?

**Comment by cchance27** [comment]
Just wanted to chime in as you mentioned ethical issues with releasing the full version of the model, I wonder to an extent if it's not a commercial issue over an ethical one, as it is Voice Cloning commercial services are pretty easily accessed most of which basically amount to clicking a checkmark that says "sure I have the rights to this voice" with extreme fidelity, so I think the cat is already out of the bag when it comes to voice cloning at this point. 

Open sourcing models just flattens the playing field with those that can't afford to pay per token pricing and rather wait for models to run on our slower hardware, especially in lower income areas of the world that still want to experiment with technology.

Regardless of the full model release, will be cool to test the half-res model to see how it compares against the stuff coming out of the big projects like meta and microsoft

**Comment by egoist-sx** [comment]
code and model released.
