### ISSUE TITLE
Upgrading to V2, torch version conflicts with MeloTTS

### ISSUE THREAD

**Issue by neoyxm** [myshell-ai/OpenVoice#203]
OpenVoice needs torch 2.xx, but MeloTTS needs torch 1.xx .

Is that possible to upgrade the MeloTTS torch version to 2.xx ??

**Comment by cnhanbing** [comment]
Also encountered this problem, please ask how to solve

**Comment by FaisalAhmed-NSL** [comment]
Got this error also when upgrade to V2
from melo.api import TTS
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
