### ISSUE TITLE
Models on the Hugging Face Hub!

### ISSUE THREAD

**Issue by Vaibhavs10** [myshell-ai/OpenVoice#21]
Hi myshell team,

I'm VB, I lead the developer advocacy efforts for Audio at Hugging Face. Congratulations on releasing such a brilliant checkpoint.

It'd also be nice to upload the model weights to the hub. This would also increase the visibility of the model checkpoint, hence leading to adoption.

The process to do is quite simple:
1. Under the https://huggingface.co/myshell-ai org create a new model.
2. Upload checkpoints to the repo.
3. Add a model card (similar to GitHub README)

Of course, I am happy to help/ guide you if you have any questions.

Cheers,
VB

**Comment by egoist-sx** [comment]
https://huggingface.co/spaces/myshell-ai/OpenVoice

Here you go

**Comment by Vaibhavs10** [comment]
Hi @egoist-sx - Love the space. I was talking about uploading the model weights (https://myshell-public-repo-hosting.s3.amazonaws.com/checkpoints_1226.zip) seperately in the same org.

**Comment by egoist-sx** [comment]
Let me work on this with our research team

**Comment by Vaibhavs10** [comment]
Awesome! I see that it is up now: https://huggingface.co/myshell-ai/OpenVoice

Will close the issue!

**Comment by marshalleq** [comment]
The model seems to no longer be available, all I get is a message saying it has been permanently disabled.  Is this an error or is it truly disabled?  Anyone know where we get the model from for v2?
`<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>DHP94NF7535Q1W13</RequestId>
<HostId>
EiLrxcrA8pgTG72vpbQsfrl3CwJAY9nBVuVSPtI5A0vGHLipddBZQYAqIu2tDktppexrM29gAAFeV7on7u7Cxg==
</HostId>
</Error>`

**Comment by BitReign** [comment]
> The model seems to no longer be available, all I get is a message saying it has been permanently disabled. Is this an error or is it truly disabled? Anyone know where we get the model from for v2? `<Error> <Code>AllAccessDisabled</Code> <Message>All access to this object has been disabled</Message> <RequestId>DHP94NF7535Q1W13</RequestId> <HostId> EiLrxcrA8pgTG72vpbQsfrl3CwJAY9nBVuVSPtI5A0vGHLipddBZQYAqIu2tDktppexrM29gAAFeV7on7u7Cxg== </HostId> </Error>`

There you go: https://huggingface.co/camenduru/OpenVoice/resolve/main/checkpoints_1226.zip
