### ISSUE TITLE
Does the "torch.cuda.is_available()" option affect kernel crash?

### ISSUE THREAD

**Issue by Victini00** [myshell-ai/OpenVoice#228]
While running demo_part3.ipynb, cell 3 crashes due to kernel issue.

![image](https://github.com/myshell-ai/OpenVoice/assets/87114100/091b8089-aea3-4db0-865c-2740debdef87)

I think this is due to torch.cuda.is_available() option. I found that torch.cuda.is_available() is False on cell 2.

Am I right? If yes, should I make torch.. available() true by setting torch and cuda environment? my cuda version is 12.1.

Thanks for reading it.

**Comment by Dan-H-Muniz-Sanchez** [comment]
I had the same problem (in COLAB and Vscode) this is what i did 

1.  Install Pytorch Cuda using the command in this page : https://pytorch.org/get-started/locally/ , be sure pytorch use cuda correctly , with  torch.cuda.is_available() get in true giving to you true
2. Use a env Python 3.9.XX (I use 3.9.19)

**Comment by Victini00** [comment]
@Dan-H-Muniz-Sanchez Thanks!!!!
