### ISSUE TITLE
v2 demo_part3 error

### ISSUE THREAD

**Issue by zhjygit** [myshell-ai/OpenVoice#239]
Speed is adjustable
speed = 1.0

for language, text in texts.items(): model = TTS(language=language, device=device) speaker_ids = model.hps.data.spk2id

for speaker_key in speaker_ids.keys():
    speaker_id = speaker_ids[speaker_key]
    speaker_key = speaker_key.lower().replace('_', '-')
    
    source_se = torch.load(f'checkpoints_v2/base_speakers/ses/{speaker_key}.pth', map_location=device)
    model.tts_to_file(text, speaker_id, src_path, speed=speed)
    save_path = f'{output_dir}/output_v2_{speaker_key}.wav'

    # Run the tone color converter
    encode_message = "@MyShell"
    tone_color_converter.convert(
        audio_src_path=src_path, 
        src_se=source_se, 
        tgt_se=target_se, 
        output_path=save_path,
        message=encode_message)
![image](https://github.com/myshell-ai/OpenVoice/assets/44870751/357b3967-1cc9-4c22-a76c-bd7eb61b7286)
![image](https://github.com/myshell-ai/OpenVoice/assets/44870751/a41ef2ec-6922-435e-ae96-b8e727544426)

**Comment by Zengyi-Qin** [comment]
It's the network error.

**Comment by zhjygit** [comment]
However, i can visit the file via web browser, just like visit google.com.

**Comment by zhjygit** [comment]
已经解决了。通过降级urllibs和requests包即可。后面还是会下载1-2个G的模型包，主要是语言类的，最好还是有vpn支持。
