### ISSUE TITLE
Gradio demo available and linked locally

### ISSUE THREAD

**Issue by yvrjsharma** [myshell-ai/OpenVoice#27]
The demo on Spaces is awesome! It would also be great to have the [Gradio demo](https://huggingface.co/spaces/myshell-ai/OpenVoice) available locally. This could help the community easily clone and test the model on their local hardware.

**Comment by Zengyi-Qin** [comment]
Already started working on it. Will let you know when we add it

**Comment by Zengyi-Qin** [comment]
Added 
![image](https://github.com/myshell-ai/OpenVoice/assets/40556743/4f5b3b14-7084-4189-baac-5947240d8b00)

**Comment by yvrjsharma** [comment]
Brilliant! Thanks for the response and for adding the demo locally 🙌

**Comment by KChalermdit** [comment]
langid is missing in the requirements.txt
