### ISSUE TITLE
Is it possible to generate a real-time processed voice?

### ISSUE THREAD

**Issue by michaeloo0** [myshell-ai/OpenVoice#28]
Use case:
**Meeting with foreigners**

**Comment by Zengyi-Qin** [comment]
This is doable but with a lot of engineering effort. You can actually do video chat with some bots on MyShell such as this one https://app.myshell.ai/bot/vEvm2q/6958

**Comment by michaeloo0** [comment]
Thanks~  this case could significantly enhances the global company's efficiency.

**Comment by printlin** [comment]
我已经完成了实时语音生成的工作，您可以查看：https://github.com/myshell-ai/OpenVoice/issues/54
I have completed the real-time voice generation work, you can check it: https://github.com/myshell-ai/OpenVoice/issues/54

**Comment by michaeloo0** [comment]
Amazing！ I'll feedback after try!!

**Comment by Arunprakaash** [comment]
I have created a streaming websocket server where it outputs audio chunks as it being processed and also accepts text streaming as input and outputs audio stream

github: https://github.com/Arunprakaash/openvoice.streaming.server
