### ISSUE TITLE
Kernel crash in cell 3 demo_part3.ipynb openvoice v2 windows.

### ISSUE THREAD

**Issue by yuyangji** [myshell-ai/OpenVoice#317]
Running the following code cell 3 will cause the kernel to crash. 
`reference_speaker = 'resources/example_reference.mp3' # This is the voice you want to clone
target_se, audio_name = se_extractor.get_se(reference_speaker, tone_color_converter, vad=False)`

Cuda is installed correctly
```
print(f"PyTorch CUDA build version: {torch.version.cuda}")
print("Is CUDA available: ", torch.cuda.is_available())
print("CUDA version: ", torch.version.cuda)
print("cuDNN version: ", torch.backends.cudnn.version())
print("Number of GPUs: ", torch.cuda.device_count())

```
Output
PyTorch CUDA build version: 12.4
Is CUDA available:  True
CUDA version:  12.4
cuDNN version:  90100
Number of GPUs:  1

##
Specs
Windows 11
RTX 3070
##

Jupyter log Error
------
03:29:33.598 [error] Disposing session as kernel process died ExitCode: 3221226505, Reason: 

--------------
![image](https://github.com/user-attachments/assets/5f442575-fd01-4dfc-8179-e87e7bb0760a)

**Comment by gredin** [comment]
@yuyangji Could you explain your solution?

**Comment by gredin** [comment]
P.S. This worked for me: https://github.com/myshell-ai/OpenVoice/issues/186#issuecomment-2121045158
