### ISSUE TITLE
`FileNotFoundError` on Windows

### ISSUE THREAD

**Issue by yanxiaodi** [myshell-ai/OpenVoice#34]
Not sure if you support Windows but I tried to run the `demo_part1.ipybn` in VS Code Jupyter then got an error:
![image](https://github.com/myshell-ai/OpenVoice/assets/3395915/62298a87-8380-4466-8b02-7316e060949c)

I'm not very familiar with Python but I guess there's something wrong about the file path. Could anyone please show me how to run the demo on Windows? Thanks.

**Comment by Zengyi-Qin** [comment]
Could you show your folder structure including all subfolders

**Comment by yanxiaodi** [comment]
![image](https://github.com/myshell-ai/OpenVoice/assets/3395915/96018fdd-76ac-458a-b981-0329f015fb30)
The repo is cloned at `C:\AI\OpenVoice`. No changes for any subfolders.

**Comment by Djamel-Touati2108** [comment]
im having the same error :(

**Comment by Djamel-Touati2108** [comment]
tried conda install ffmpeg and it worked just fine

**Comment by yanxiaodi** [comment]
Thanks @Djamel-Touati2108 ! Yes it works now. Previously I tried to use `pip install ffmpeg` but not working. So I should use `conda install ffmpeg` then it works. Thanks again!

@Zengyi-Qin  This issue can be closed. Thanks.
