### ISSUE TITLE
cuda 11.7.*  does not exist (perhaps a missing channel)

### ISSUE THREAD

**Issue by dmitry-js** [myshell-ai/OpenVoice#38]
`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`

Channels:
 - pytorch
 - nvidia
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides cuda 11.7.* needed by pytorch-cuda-11.7-h67b0de4_0

Could not solve for environment specs
The following package could not be installed
└─ pytorch-cuda 11.7**  is not installable because it requires
   └─ cuda 11.7.* , which does not exist (perhaps a missing channel).

**Comment by JuvenileLocksmith** [comment]
Looks like you are on a mac, won't be possible

**Comment by dmitry-js** [comment]
@JuvenileLocksmith i've already solved 
1. `conda install pytorch::pytorch-cuda`
2. `conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 -c pytorch -c nvidia`

**Comment by mutoo** [comment]
I am a Macbook M2 user, and here is my workaround:
1. you don't need to install the `pytorch-cuda`. Simply remove that entry from the conda install command:
```
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 -c pytorch -c nvidia
```
2. in the jupyter notebook, replace `device = 'cuda:0'` with `device = 'cpu'` in the Initialization step

It works like a charm.
