### ISSUE TITLE
Chinese pronunciation needs improvement

### ISSUE THREAD

**Issue by luohao123** [myshell-ai/OpenVoice#4]
你好，demo里面中文的音调感觉不太正常，早是三声，但是读不能读三声，是否有计划吧中文语调支持更完善一下？

**Comment by egoist-sx** [comment]
updating base model for CN

**Comment by Zengyi-Qin** [comment]
Chinese base speaker added. Please see demo_part1.ipynb

**Comment by luohao123** [comment]
Any audio sample?

**Comment by luohao123** [comment]
Listened the new mp4 Chinese pronounce didn't get better

**Comment by Zengyi-Qin** [comment]
It's not in the video. It's in demo_part1.ipynb.

**Comment by luohao123** [comment]
@Zengyi-Qin I can not run the code due to complciated env setup, does there any voice demo?

**Comment by Zengyi-Qin** [comment]
The env setup should be very basic and easy. What specific issue did you encounter?

**Comment by Zengyi-Qin** [comment]
Hi - I wonder if you have any follow-up questions. We will consider closing this issue if there's no follup-ups

**Comment by Zengyi-Qin** [comment]
inactive
