### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by MiniNoller** [myshell-ai/OpenVoice#52]
Will this support Linux at some point? If yes, when?

**Comment by agronholm** [comment]
I haven't tried this myself yet, but is there anything OS specific in the requirements that would prevent installation or use on Linux?

**Comment by RodTDai** [comment]
after following the install instructions i'm getting this:

python3.10 -m openvoice_app --share

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/rod/4TDATA/AI_TOOLS/OpenVoice/OpenVoice/openvoice_app.py", line 6, in <module>
    import langid
ModuleNotFoundError: No module named 'langid'

Help please!

**Comment by agronholm** [comment]
It seems that you're not even using a virtualenv?

**Comment by agronholm** [comment]
The installation instructions don't seem to be very reasonable.

**Comment by RodTDai** [comment]
in the end i installed the missing elements manually with help of google Bard.
thanks guys
