### ISSUE TITLE
Cant install and run project

### ISSUE THREAD

**Issue by maxi74x1** [myshell-ai/OpenVoice#59]
after i install all the requirements and start up the openvoice_app.py it spits out an error saying "[Errno 2] No such file or directory: 'checkpoints/base_speakers/EN/config.json' "

**Comment by basher0** [comment]
first you have to download and extract the checkpoint to the base folder 
https://huggingface.co/camenduru/OpenVoice/resolve/main/checkpoints_1226.zip
