### ISSUE TITLE
Error on Debian (libcudnn_cnn_infer.so.8)

### ISSUE THREAD

**Issue by MiniNoller** [myshell-ai/OpenVoice#63]
`Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory`

**Comment by SerCeMan** [comment]
I had the same issue, and in my case, installing cudnn inside the conda env helped to resolve it. 

```
conda install -c anaconda cudnn
```

**Comment by visjble** [comment]
I did install cudnn but still having the same error. Any int on how to fix it? THanks:
`conda install -c anaconda cudnn
Channels:
 - anaconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
`

`UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Loaded checkpoint 'checkpoints_v2/converter/checkpoint.pth'
missing/unexpected keys: [] []
OpenVoice version: v2
Could not load library libcudnn_cnn_infer.so.8. Error: libcudnn_cnn_infer.so.8:`

**Comment by visjble** [comment]
I seems I made some progress by:
changing the deprecated offending lines in modules.py and weight_norm.py
sudo apt-get install libcublas-11-0
exporting library path
conda install -c conda-forge cudatoolkit=11
