### ISSUE TITLE
FileNotFoundError: [Errno 1] No such file or directory: 'checkpoints/base_speakers/EN/config.json'

### ISSUE THREAD

**Issue by ENDERMANHEY** [myshell-ai/OpenVoice#70]
i have no ideo why im getting this error can someone help me? i am new to this stuff.

**Comment by Me-Phew** [comment]
From the project README
> Download the checkpoint from [here](https://myshell-public-repo-hosting.s3.amazonaws.com/checkpoints_1226.zip) and extract it to the checkpoints folder

Most likely you've missed that step

**Comment by ENDERMANHEY** [comment]
Ahh! Looks like i made a foolish mistake. Thanks!

**Comment by MosiGeek** [comment]
checkpoints folder not found! Returning an error if you try to download the checkpoints folder. "All access to this object has been disabled"

**Comment by unaiLopez** [comment]
It seems that the link to download the checkpoints is not public anymore. Anyone knows any workaround to get this checkpoints? Thank you!

**Comment by Parul-INT00004** [comment]
clone the repo from here:
https://huggingface.co/myshell-ai/OpenVoice

**Comment by skykingjwc** [comment]
> From the project README
> 
> > Download the checkpoint from [here](https://myshell-public-repo-hosting.s3.amazonaws.com/checkpoints_1226.zip) and extract it to the checkpoints folder
> 
> Most likely you've missed that step

It's not in there anymore.  They removed all reference to it for some reason.
