### ISSUE TITLE
Question about input data while training convertor

### ISSUE THREAD

**Issue by ethanyhzhang** [myshell-ai/OpenVoice#9]
Hi,
    Thanks for the great idea of your works! Here is a question.
    When training the convertor, the paper shows that lots of audio all collected. So for a sample like ( text_1, audio_1 ), what's the input audio of the convertor(encoder)? audio_1 or the audio_x generated by the base tts using the text_1? 

    * if audio_1, it seems that input equals output?
    * if audio_x, would the convertor too strongly related to the base TTS (the generated voice) ?

    looking for your reply. thanks again.

**Comment by Zengyi-Qin** [comment]
It's audio_1

**Comment by ethanyhzhang** [comment]
> It's audio_1

Thanks. Seems that KL between IPA sequence features and Z really works.

**Comment by ethanyhzhang** [comment]
> > It's audio_1
> 
> Thanks. Seems that KL between IPA sequence features and Z really works.

Sorry for another question: what's the reference audio during convertor training? Also the audio_1? or other audio of the same speaker?

**Comment by Zengyi-Qin** [comment]
It's also audio_1

**Comment by ethanyhzhang** [comment]
many thanks.
